train_prompt: |
  Below is an instruction that describes a task, paired with an input that provides further context.
  Write a response that appropriately completes the request.
  Before answering, think carefully about the question and create a step-by-step chain of thoughts to ensure a logical and accurate response.

  ### Instruction:
  You are a medical expert with advanced knowledge in clinical reasoning, diagnostics, and treatment planning.
  Please answer the following medical question.

  ### Question:
  {}

  ### Response:
  <think>
  {}
  </think>
  {}